export const MOCK_DATA = [
  {
    diaryId: 1,
    createdDate: '2024-05-20T11:15',
    authorProfile: 'ex-profile.svg',
    author: '김경주',
    petProfile: 'ex-profile.svg',
    contentImages: ['asdmalkfgmasldmlkmsad.jpg', 'asndanmsfmnasfmoaskm.jpg'],
    content: '오늘 뽀삐랑 같이 산책을 다녀왔어! 오늘 뽀삐랑 같이 산책을 다녀왔어!',
    commentCount: 1,
    favoriteCount: 0,
    favoriteState: false,
    isMyDiary: true,
  },
  {
    diaryId: 2,
    createdDate: '2024-05-21T12:30',
    authorProfile: 'ex-profile.svg',
    author: '문지혜',
    petProfile: 'ex-profile.svg',
    contentImages: ['oneMoreImage.jpg', 'yetAnotherImage.jpg'],
    content: '밥도먹었어요',
    commentCount: 2,
    favoriteCount: 3,
    favoriteState: true,
    isMyDiary: false,
  },
  {
    diaryId: 3,
    createdDate: '2024-05-21T12:30',
    authorProfile: 'ex-profile.svg',
    author: '이동현',
    petProfile: 'ex-profile.svg',
    contentImages: ['oneMoreImage.jpg', 'yetAnotherImage.jpg'],
    content: '강아지 놀이터 가서 놀다 왔어요',
    commentCount: 0,
    favoriteCount: 3,
    favoriteState: false,
    isMyDiary: false,
  },
  {
    diaryId: 4,
    createdDate: '2024-05-21T12:30',
    authorProfile: 'ex-profile.svg',
    author: '임동현',
    petProfile: 'ex-profile.svg',
    contentImages: ['oneMoreImage.jpg', 'yetAnotherImage.jpg'],
    content: '예방접종 받은 날',
    commentCount: 2,
    favoriteCount: 3,
    favoriteState: true,
    isMyDiary: true,
  },
  {
    diaryId: 5,
    createdDate: '2024-05-21T12:30',
    authorProfile: 'ex-profile.svg',
    author: '조한빈',
    petProfile: 'ex-profile.svg',
    contentImages: ['oneMoreImage.jpg', 'yetAnotherImage.jpg'],
    content: '흠냐',
    commentCount: 0,
    favoriteCount: 0,
    favoriteState: false,
    isMyDiary: false,
  },
];
